module.exports = {
  "login": "damenor",
  "id": 18181907,
  "node_id": "MDQ6VXNlcjE4MTgxOTA3",
  "avatar_url": "https://avatars1.githubusercontent.com/u/18181907?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/damenor",
  "html_url": "https://github.com/damenor",
  "followers_url": "https://api.github.com/users/damenor/followers",
  "following_url": "https://api.github.com/users/damenor/following{/other_user}",
  "gists_url": "https://api.github.com/users/damenor/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/damenor/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/damenor/subscriptions",
  "organizations_url": "https://api.github.com/users/damenor/orgs",
  "repos_url": "https://api.github.com/users/damenor/repos",
  "events_url": "https://api.github.com/users/damenor/events{/privacy}",
  "received_events_url": "https://api.github.com/users/damenor/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 28,
  "public_gists": 0,
  "followers": 1,
  "following": 2,
  "created_at": "2016-03-31T04:00:09Z",
  "updated_at": "2020-10-11T07:27:52Z"
  }
  