module.exports = {
  "login": "rmenor",
  "id": 531622,
  "node_id": "MDQ6VXNlcjUzMTYyMg==",
  "avatar_url": "https://avatars1.githubusercontent.com/u/531622?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/rmenor",
  "html_url": "https://github.com/rmenor",
  "followers_url": "https://api.github.com/users/rmenor/followers",
  "following_url": "https://api.github.com/users/rmenor/following{/other_user}",
  "gists_url": "https://api.github.com/users/rmenor/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/rmenor/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/rmenor/subscriptions",
  "organizations_url": "https://api.github.com/users/rmenor/orgs",
  "repos_url": "https://api.github.com/users/rmenor/repos",
  "events_url": "https://api.github.com/users/rmenor/events{/privacy}",
  "received_events_url": "https://api.github.com/users/rmenor/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ramón Menor",
  "company": null,
  "blog": "www.ramonmenor.es",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 4,
  "public_gists": 0,
  "followers": 5,
  "following": 2,
  "created_at": "2010-12-21T08:15:04Z",
  "updated_at": "2020-10-11T23:00:16Z"
  }
  